"""Git infrastructure layer — subprocess wrappers and porcelain parsing."""

from gitz.git.exceptions import GitError
from gitz.git.commands import (
    commit,
    get_branches,
    get_commit_log,
    get_current_branch,
    get_default_branch,
    get_file_diff,
    get_git_dir,
    get_head_summary,
    get_operation_state,
    get_remote_status,
    get_repo_info,
    get_staged_diff,
    get_staged_file_diff,
    get_status,
    get_user,
    is_detached_head,
    is_merge_in_progress,
    is_rebase_in_progress,
    push,
    stage,
    switch_branch,
    unstage,
)

__all__ = [
    "GitError",
    "commit",
    "get_branches",
    "get_commit_log",
    "get_current_branch",
    "get_default_branch",
    "get_file_diff",
    "get_git_dir",
    "get_head_summary",
    "get_operation_state",
    "get_remote_status",
    "get_repo_info",
    "get_staged_diff",
    "get_staged_file_diff",
    "get_status",
    "get_user",
    "is_detached_head",
    "is_merge_in_progress",
    "is_rebase_in_progress",
    "push",
    "stage",
    "switch_branch",
    "unstage",
]
